# Generated by Django 5.2.8 on 2025-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('udioUVlasnistvu', models.FloatField(default=0.0)),
                ('sifKorisnik', models.AutoField(primary_key=True, serialize=False)),
                ('korisnickoIme', models.CharField(max_length=50, unique=True)),
                ('uloga', models.CharField(choices=[('s', 'Suvlasnik'), ('ps', 'Predstavnik suvlasnika'), ('a', 'Administrator')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
