# Generated by Django 5.2.8 on 2025-11-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_korisnik_is_staff_korisnik_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
