# Generated by Django 5.2.8 on 2025-11-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_korisnik_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='has_module_perms',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='is_superuser',
        ),
    ]
