# Generated by Django 5.2.8 on 2025-11-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_korisnik_has_module_perms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
