# Generated by Django 5.2.8 on 2025-11-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_korisnik_is_staff_korisnik_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='is_superuser',
        ),
    ]
