# Generated by Django 5.2.8 on 2025-11-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_korisnik_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
