# Generated by Django 5.2.8 on 2025-11-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_korisnik_groups_korisnik_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='sifKorisnik',
            new_name='id',
        ),
    ]
