# Generated by Django 5.2.8 on 2025-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_korisnik_googleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='googleID',
            field=models.CharField(default='', null=True, unique=True),
        ),
    ]
