# Generated by Django 5.2.8 on 2025-11-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_korisnik_googleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='googleID',
        ),
    ]
